### ISSUE TITLE
A multi-gpu training bug

### ISSUE THREAD

**Issue by mayfool** [rishikksh20/iSTFTNet-pytorch#1]
stft.py line 164->165:
window_sum = window_sum.cuda() if magnitude.is_cuda else window_sum
inverse_transform[:, :, approx_nonzero_indices] /= window_sum[approx_nonzero_indices], 
would get errors . Because, inverse_transform might in cuda1 while window_sum in cuda0.
Change line 164 to window_sum = window_sum.to(inverse_transform.device()) if magnitude.is_cuda else window_sum will fix the problem.

**Comment by rishikksh20** [comment]
thanks will do that
