### ISSUE TITLE
Different sample rate

### ISSUE THREAD

**Issue by wizardk** [rishikksh20/iSTFTNet-pytorch#12]
Hi @rishikksh20  , thanks for your work.

I have a question. If I want to use the 16K sampling rate, how do I modify the configuration file?
It should not just modify sampling_rate in json.

**Comment by rishikksh20** [comment]
You needed to change sample rate and `upsample_rates` and other upsample related params which depending on your hop length

**Comment by wizardk** [comment]
> You needed to change sample rate and `upsample_rates` and other upsample related params which depending on your hop length

thanks.
