### ISSUE TITLE
Pretrained models

### ISSUE THREAD

**Issue by egorsmkv** [rishikksh20/iSTFTNet-pytorch#13]
Hello, thank you very much for this repo

Can you please provide pre-trained models for tests?

**Comment by rishikksh20** [comment]
@egorsmkv I train this model on private proprietary dataset so can't share the pretrained models, but I test this in more than 20 voices and it worked great every time.

**Comment by egorsmkv** [comment]
How much tie did you train a model? and which GPUs did you use?

**Comment by rishikksh20** [comment]
200k training is enough to generate good quality of voice, I used V100 and it takes 1 day to complete the training

**Comment by egorsmkv** [comment]
Thanks, @rishikksh20
